SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Allan Albacete
-- Create date: 04/08/2013
-- Description:	Resigned Members
-- =============================================
CREATE PROCEDURE emed_resigned_members_principal
	-- Add the parameters for the stored procedure here
	@AccountCode as varchar(25)
AS
BEGIN
	SELECT	H.AREA_DESC, A.PRIN_CODE, A.MEM_LNAME, A.MEM_FNAME, A.MEM_MI, A.MEM_BDAY, A.MEM_AGE, F.SEX_DESC, E.MEMCSTAT_DESC, A.EFF_DATE, A.VAL_DATE, D.PLAN_DESC, A.DATE_RESGN,isnull(A.PRIN_COMPID,'') AS PRIN_COMPID 
						FROM SYS_UWPRINCIPAL_ACTIVE_MTBL A 
							INNER JOIN SYS_ACCOUNT_MTBL B ON A.ACCOUNT_CODE=B.ACCOUNT_CODE 
							LEFT JOIN SYS_ROOMRATE_MTBL C ON A.RSPROOMRATE_ID=C.RSPROOMRATE_ID 
							LEFT JOIN SYS_PLAN_LTBL D ON C.PLAN_CODE=D.PLAN_CODE 
							LEFT JOIN SYS_UWMEMBER_CSTATUS_LTBL E ON A.MEM_CIVILSTAT=E.MEMCSTAT_ID 
							LEFT JOIN SYS_MEM_S_LTBL F ON A.MEM_SEX=F.SEXID 
							LEFT JOIN SYS_UWMEMBER_OSTATUS_LTBL G ON A.MEM_OSTAT_CODE=G.MEMOSTAT_ID 
							LEFT JOIN SYS_AREA_LTBL H ON A.AREA_CODE=H.AREA_CODE 
							LEFT JOIN SYS_ACCTTYPE_LTBL J ON B.ACCTTYPE_CODE = J.ACCTTYPE_CODE 
							INNER JOIN SYS_UWMEMBER_OSTATUS_LTBL L ON A.MEM_OSTAT_CODE = L.MEMOSTAT_ID 
						WHERE 
							a.account_code in (@AccountCode)  and 
							A.MEM_OSTAT_CODE in (9) and 
							a.val_date  >= GETDATE() 
						ORDER BY B.ACCOUNT_NAME, h.area_desc, A.MEM_LNAME, A.MEM_FNAME, A.MEM_MI
END
GO
