'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BenfitsExclusions1

    '''<summary>
    '''RadTabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''RadMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''RadPageView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblLapSurgP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLapSurgP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblChemoP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChemoP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRIP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHumBloodP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHumBloodP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComplexDiagP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComplexDiagP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWorkIllP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWorkIllP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOrgTrans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrgTrans As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCongIllP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCongIllP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOpenSurgP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpenSurgP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCataractP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCataractP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPTP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAntiRabP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAntiRabP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLTGlaucuomaP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLTGlaucuomaP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hcsOtherPRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hcsOtherPRN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgHCSOtherPRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgHCSOtherPRN As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblLapSurgQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLapSurgQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblChemoQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChemoQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRIQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRIQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHumBloodQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHumBloodQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComplexDiagQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComplexDiagQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWorkIllQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWorkIllQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCongIllQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCongIllQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOpenSurgQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpenSurgQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCataractQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCataractQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPTQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPTQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAntiRabQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAntiRabQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLTGlaucuomaQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLTGlaucuomaQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hcsOtherDEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hcsOtherDEP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgHCSOtherDEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgHCSOtherDEP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblLapSurg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLapSurg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblChemo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChemo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHumBlood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHumBlood As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComplexDiag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComplexDiag As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWorkIll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWorkIll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCongIll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCongIll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOpenSurg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpenSurg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCataract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCataract As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAntiRab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAntiRab As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLTGlaucuoma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLTGlaucuoma As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hcsOtherEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hcsOtherEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgHCSOtherEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgHCSOtherEXT As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''standardHCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents standardHCS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadPageView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''imgMedHOP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgMedHOP As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgCompPremP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCompPremP As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgNearHospP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNearHospP As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblECGP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblECGP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPapsmearP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPapsmearP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgEyeRefP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEyeRefP As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''phcsOtherPRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phcsOtherPRN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgPHCSOtherPRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgPHCSOtherPRN As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''imgMedHOQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgMedHOQ As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgCompPremQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCompPremQ As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgNearHospQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNearHospQ As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblECGQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblECGQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPapsmearQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPapsmearQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgEyeRefQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEyeRefQ As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''phcsOtherDEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phcsOtherDEP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgPHCSOtherDEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgPHCSOtherDEP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''imgMedHOE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgMedHOE As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgCompPremE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCompPremE As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgNearHospE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNearHospE As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblECGE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblECGE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPapsmearE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPapsmearE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgEyeRefE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEyeRefE As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''phcsOtherEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phcsOtherEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgPHCSOtherEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgPHCSOtherEXT As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''standardPHCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents standardPHCS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadPageView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''tblContentP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblContentP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ecsOtherPRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ecsOtherPRN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgECSOtherPRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgECSOtherPRN As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblContentQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblContentQ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ecsOtherDEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ecsOtherDEP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgECSOtherDEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgECSOtherDEP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblContentE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblContentE As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ecsOtherEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ecsOtherEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgECSOtherEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgECSOtherEXT As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''standardECS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents standardECS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadPageView4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView4 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''tblMFAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMFAP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mfaOtherPRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mfaOtherPRN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgMFAOtherPRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgMFAOtherPRN As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblMFAQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMFAQ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mfaOtherDEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mfaOtherDEP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgMFAOtherDEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgMFAOtherDEP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblMFAE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMFAE As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mfaOtherEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mfaOtherEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgMFAOtherEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgMFAOtherEXT As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''standardMFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents standardMFA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadPageView5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView5 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblFillingP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFillingP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProphylaxisP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProphylaxisP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLigtCureP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLigtCureP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dcsOtherPRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcsOtherPRN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgDCSOtherPRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgDCSOtherPRN As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblFillingQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFillingQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProphylaxisQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProphylaxisQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLigtCureQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLigtCureQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dcsOtherDEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcsOtherDEP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgDCSOtherDEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgDCSOtherDEP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblFillingE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFillingE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProphylaxisE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProphylaxisE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLigtCureE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLigtCureE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dcsOtherEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcsOtherEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgDCSOtherEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgDCSOtherEXT As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''standardDCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents standardDCS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadPageView6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView6 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''DivExclusion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivExclusion As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadPageView7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView7 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''tblPECP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPECP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pecOtherPRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pecOtherPRN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgOthersPECP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgOthersPECP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblPECD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPECD As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pecOtherDEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pecOtherDEP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgOthersPECD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgOthersPECD As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblPECE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPECE As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pecOtherEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pecOtherEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgOthersPECE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgOthersPECE As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''standardPEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents standardPEC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadPageView8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView8 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''posContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents posContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadPageView9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView9 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''matContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents matContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''matOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents matOther As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dtgMatOthers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgMatOthers As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''RadPageView10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView10 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''execContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents execContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadPageView11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView11 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''drdContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drdContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadPageView12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView12 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''meContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
