Imports emedicardBLL
Imports System.IO

Public Class RequesDetails
    Inherits System.Web.UI.Page
    Dim key As String = ConfigurationManager.AppSettings("encryptionKey")
    Dim dtRequest As DataTable

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        If Not IsPostBack Then
            buttonDisabler()

            GetAllRequestList()
        End If
    End Sub

    Private Sub GetAllRequestList()
        'GetCorporateRequestListAll
        Try
            Using bll = New eCorporateBLL
                If Request.QueryString("t") = "1" Then
                    bll.UserType = 1
                ElseIf Request.QueryString("t") = "2" Then
                    bll.UserType = 2
                Else
                    Exit Sub
                End If
                bll.AccountCode = Request.QueryString("a")
                bll.record_id = EncryptDecrypt.EncryptDecrypt.Decrypt(Request.QueryString("dtl"), key)
                dtRequest = bll.GetRequestDetail
                RepDetails.DataSource = dtRequest
                RepDetails.DataBind()

                bll.UpdateRequestViews()
            End Using
        Catch ex As Exception

        End Try
    End Sub

    Private Sub buttonDisabler()
        'SOLUTION 2: CHANGE THE BUTTON SUBMIT JS CODE SO THAT IT

        'DISABLES WHEN THE FORM IS VALID, PRIOR TO SUBMISSION

        'build the JS

        Dim sb As New StringBuilder()

        sb.Append("if (typeof(Page_ClientValidate) == 'function') { ")

        'if client-side does not validate, stop (this supports validation groups)

        'BUGFIX: must save, then restore the page validation / submission state, otherwise

        'when the validation fails, it prevents the FIRST autopostback from other controls

        sb.Append("var oldPage_IsValid = Page_IsValid; var oldPage_BlockSubmit = Page_BlockSubmit;")

        sb.Append("if (Page_ClientValidate('" + btnUpload.ValidationGroup & "') == false) {")

        sb.Append(" Page_IsValid = oldPage_IsValid; Page_BlockSubmit = oldPage_BlockSubmit; return false; }} ")

        'change button text and disable it

        sb.Append("this.value = 'Processing...';")

        sb.Append("this.disabled = true;")

        'insert the call to the framework JS code that does the postback of the form in the client

        'The default code generated by ASP (WebForm_DoPostbackWithOptions) will not

        'submit because the button is disabled (this is new in 2.0)

        sb.Append(ClientScript.GetPostBackEventReference(btnUpload, Nothing) & ";")

        'BUGFIX: MUST RETURN AFTER THIS, OTHERWISE IF THE BUTTON HAS UseSubmitBehavior=false

        'THEN ONE CLICK WILL IN FACT CAUSE 2 SUBMITS, DEFEATING THE WHOLE PURPOSE

        sb.Append("return true;")

        Dim submit_button_onclick_js As String = sb.ToString()

        btnUpload.Attributes.Add("onclick", submit_button_onclick_js)

    End Sub

    Protected Sub RepDetails_ItemCommand(ByVal source As Object, ByVal e As System.Web.UI.WebControls.RepeaterCommandEventArgs) Handles RepDetails.ItemCommand
        If e.CommandName = "Download" Then
            Dim iIndex As Integer = e.Item.ItemIndex
            Dim srecid As String = String.Empty
            For Each ctr In e.Item.Controls
                If TypeOf (ctr) Is HiddenField Then
                    Dim hdn As New HiddenField
                    hdn = ctr
                    srecid = hdn.Value
                End If
            Next

            Dim dtRec As New DataTable
            Using bll = New eCorporateBLL

                bll.AccountCode = Request.QueryString("a")
                bll.record_id = srecid
                dtRec = bll.GetRequestDetail

                Dim sFilename As String = String.Empty

                sFilename = dtRec(0)(2)

                If Trim(sFilename) <> "" Then

                End If

                If sFilename.Contains(";") Then
                    Dim sp As String()
                    sp = sFilename.Split(New Char() {";"c})
                    For Each fname As String In sp
                        Response.Clear()

                        Response.ClearContent()
                        Response.ClearHeaders()
                        Response.BufferOutput = True

                        Response.AddHeader("Content-Disposition", "attachment; filename=" + fname)
                        Response.ContentType = "application/octet-stream"
                        Response.WriteFile(ConfigurationManager.AppSettings("UploadDir") & fname)
                        Response.End()
                    Next
                Else
                    Response.Clear()

                    Response.ClearContent()
                    Response.ClearHeaders()
                    Response.BufferOutput = True

                    Response.AddHeader("Content-Disposition", "attachment; filename=" + sFilename)
                    Response.ContentType = "application/octet-stream"
                    Response.WriteFile(ConfigurationManager.AppSettings("UploadDir") & sFilename)
                    Response.End()
                End If

                'Response.Clear()

                'Response.ClearContent()
                'Response.ClearHeaders()
                'Response.BufferOutput = True

                'Response.AddHeader("Content-Disposition", "attachment; filename=" + sFilename)
                'Response.ContentType = "application/octet-stream"
                'Response.WriteFile(ConfigurationManager.AppSettings("UploadDir") & sFilename)
                'Response.End()

                HttpContext.Current.ApplicationInstance.CompleteRequest()
            End Using
        End If

    End Sub

    Protected Sub RepDetails_ItemDataBound(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.RepeaterItemEventArgs) Handles RepDetails.ItemDataBound
        Dim sFile As String = ""

        Dim iIndex As Integer = e.Item.ItemIndex

        For Each ctr In e.Item.Controls
            If TypeOf (ctr) Is Label Then
                Dim lbl As New Label
                lbl = ctr
                If lbl.ID = "lblFilename" Then
                    sFile = lbl.Text
                    If Trim(sFile) = "" Then
                        For Each ctr2 In e.Item.Controls
                            If TypeOf (ctr2) Is Button Then
                                Dim btn As New Button
                                btn = ctr2
                                btn.Visible = False
                            End If
                        Next
                    Else
                        If sFile.Contains(";") Then
                            lbl.Text = ""
                            Dim sp As String()
                            sp = sFile.Split(New Char() {";"c})
                            For Each fname As String In sp
                                Dim flink As String = ConfigurationManager.AppSettings("BaseUrl") & "/DLPage.aspx?flname=" & HttpUtility.UrlEncode(fname)
                                lbl.Text += "<p><a href='" & flink & "' target='_blank'>" & fname & "</a></p><br/>"
                            Next
                        Else
                            lbl.Text = ""
                            Dim flink As String = ConfigurationManager.AppSettings("BaseUrl") & "/DLPage.aspx?flname=" & HttpUtility.UrlEncode(sFile)
                            lbl.Text += "<p><a href='" & flink & "' target='_blank'>" & sFile & "</a></p><br/>"
                        End If
                    End If
                End If
            End If
        Next


    End Sub

    Protected Sub btnUpload_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnUpload.Click
        If FileUpload1.HasFile Then
            Dim sext As String = Path.GetExtension(FileUpload1.PostedFile.FileName)
            If FileUpload1.PostedFile.ContentType = "application/vnd.ms-excel" Or FileUpload1.PostedFile.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" Or FileUpload1.PostedFile.ContentType = "application/x-zip-compressed" Or FileUpload1.PostedFile.ContentType = "application/pdf" Or FileUpload1.PostedFile.ContentType = "image/jpeg" Or FileUpload1.PostedFile.ContentType = "image/png" Or FileUpload1.PostedFile.ContentType = "image/gif" Or (FileUpload1.PostedFile.ContentType = "application/octet-stream" AndAlso sext = ".rar") Or FileUpload1.PostedFile.ContentType = "application/vnd.ms-excel" Then
                If FileUpload1.PostedFile.ContentLength <= 15750656 Then

                    Dim sFile As String = Now.ToString("yyyyMMdd-HHmmss") & "_" & Path.GetFileName(FileUpload1.FileName)
                    FileUpload1.SaveAs(ConfigurationManager.AppSettings("UploadDir") & sFile)
                    SaveData(sFile)

                Else
                    lblMessage.Text = "The file is too large. It must be less than or equal to 15MB."
                    lblMessage.Visible = True
                    lblMessage.CssClass = "label label-warning"
                End If
            Else
                lblMessage.Text = "The file is not allowed. The allowed files are excel(.xls, .xlsx, .csv), compressed file(.zip, .rar), pdf file, images(.jpeg, .png, .gif)"
                lblMessage.Visible = True
                lblMessage.CssClass = "label label-warning"
            End If
        Else
            SaveData("")
        End If
    End Sub

    Private Sub SaveData(ByVal sFilename As String)

        Dim sAccountName As String = String.Empty
        Dim sAgnCode As String = String.Empty
        Dim sSender As String = String.Empty

        Using bll = New eCorporateBLL
            With bll
                Dim dt1 As New DataTable
                Dim sTitle As String = String.Empty
                Dim dtEmail As New DataTable

                bll.AccountCode = Request.QueryString("a")
                bll.record_id = EncryptDecrypt.EncryptDecrypt.Decrypt(Request.QueryString("dtl"), key)
                dt1 = bll.GetRequestDetail

                For Each dr As DataRow In dt1.Rows
                    sTitle = dr("subject")
                Next

                .Remarks = Trim(txtUploadRemarks.Text)
                .file_path = sFilename
                .uploaded_by = EncryptDecrypt.EncryptDecrypt.Decrypt(Request.QueryString("u"), key)
                .Username = EncryptDecrypt.EncryptDecrypt.Decrypt(Request.QueryString("u"), key)
                .AccountCode = Request.QueryString("a")
                .Title = sTitle
                .Is_Mother = False
                .MotherID = EncryptDecrypt.EncryptDecrypt.Decrypt(Request.QueryString("dtl"), key)
                If Request.QueryString("t") = "1" Then
                    .UserType = 1
                ElseIf Request.QueryString("t") = "2" Then
                    .UserType = 2
                Else
                    Exit Sub
                End If

                .Save_Endorsement_Request()

                Using acctBLLInfo = New AccountInformationBLL(Request.QueryString("a"), 1)
                    sAccountName = acctBLLInfo.CompanyName
                    sAgnCode = acctBLLInfo.AgentCode
                End Using

                Dim sMsg As String = String.Empty

                'sMessage = "<table><tr><td>Title:</td><td><strong>" & sTitle & "</strong></td><tr><td>Created by: </td><td><strong>" & bll.User_Fullname & "</strong></td></tr></table>"
                'sMessage = sMessage & "<p>This is to inform you that a new transaction has been sent to you from eMedicard. Please <a href='https://webportal.medicardphils.com/emedicard'>log in</a> to eMedicad to see the details.</p>"
                'Mailhelper.MailHelper.SendMailMessage("noreply@medicardphils.com", sReceivers, "", "", "eMedicard Notification", sMessage)

                Using embll = New emedBLL

                    If bll.UserType = 1 Then
                        'Get eAccount
                        embll.application_type = "ecorp"
                    ElseIf bll.UserType = 2 Then
                        embll.application_type = "eaccount"
                    End If
                    If .Title = "Membership Endorsement" Or .Title = "Membership Cancellation" Then
                        embll.mail_description = .Title
                    Else
                        embll.mail_description = "File Uploading Other"
                    End If
                    embll.GetRecepients()

                    Dim dtCC As New DataTable
                    Dim sCC As String = String.Empty

                    Using oCorpBLL = New eCorporateBLL
                        oCorpBLL.AccountCode = Trim(Request.QueryString("a"))
                        oCorpBLL.GetAccountContactInfo()
                        If bll.UserType = 1 Then
                            'eCorporate
                            'Dim smail As String = embll.GetEmail("", "eaccount", sAgnCode)
                            'If embll.send_to_tag = "eaccount_main" Then
                            '    embll.send_to_email = embll.send_to_email & "," & oCorpBLL.EmailAddress
                            'End If
                        ElseIf bll.UserType = 2 Then
                            'eAccount
                            'If embll.send_to_tag = "ecorp_main" Then
                            '    embll.send_to_email = embll.send_to_email & "," & oCorpBLL.EmailAddress
                            'End If
                        End If

                        embll.prm_account_code = Trim(Request.QueryString("a"))
                        embll.prm_agent_code = sAgnCode
                        dtCC = embll.GetCC()

                        For Each dr As DataRow In dtCC.Rows
                            If Trim(sCC) = "" Then
                                sCC = dr(0)
                            Else
                                sCC = sCC & "," & dr(0)
                            End If
                        Next

                        If bll.UserType = 1 Then
                            sSender = embll.GetEmail(bll.Username, "ecorp")
                        ElseIf bll.UserType = 2 Then
                            sSender = embll.GetEmail(bll.Username, "eaccount")
                        End If

                        If Trim(embll.send_to_tag) <> "" Then
                            Select Case Trim(embll.send_to_tag)
                                Case "ecorp_main"

                                    If Trim(sCC) <> "" Then
                                        sCC = sCC & " , " & embll.GetEmail("", "ecorp", "", bll.AccountCode)
                                    Else
                                        sCC = embll.GetEmail("", "ecorp", "", bll.AccountCode)
                                    End If

                                Case "eaccount_main"

                                    If Trim(sCC) <> "" Then
                                        sCC = sCC & " , " & embll.GetEmail("", "eaccount", sAgnCode, bll.AccountCode)
                                    Else
                                        sCC = embll.GetEmail("", "eaccount", sAgnCode, bll.AccountCode)
                                    End If

                            End Select
                        End If

                        'If embll.self Then
                        '    embll.send_to_email = embll.send_to_email & ", " & sSender
                        'End If

                        If Trim(embll.send_to_email) <> "" Then
                            Dim bsent As Boolean = False
                            Dim sUserFullName As String = oCorpBLL.GetUserFullName(.uploaded_by, bll.UserType)

                            sMsg = "<p> A new reply for " & sTitle & " was filed by " & sUserFullName & " with the following details:</p>"
                            sMsg = sMsg & "<p>Reference No. : " & .MotherID & "</p>"
                            sMsg = sMsg & "<p>Filename : " & sFilename & "</p>"
                            sMsg = sMsg & "<p>Date time received : " & Now & "</p>"
                            sMsg = sMsg & "<p>Remarks : " & Trim(txtUploadRemarks.Text) & "</p>"

                            Mailhelper.MailHelper.SendMailMessage("noreply@medicardphils.com", embll.send_to_email, embll.bcc, sCC, sTitle, sMsg)
                            bsent = Mailhelper.MailHelper.Sent

                            Dim sNotifyMsg As String = String.Empty
                            If bll.UserType = 1 Then
                                sNotifyMsg = "<p>Thank you for using eCorporate!</p>"
                            ElseIf bll.UserType = 2 Then
                                sNotifyMsg = "<p>Thank you for using eAccount!</p>"
                            End If
                            sNotifyMsg = sNotifyMsg & "<p>We received your reply to  " & sTitle & ".</p>"
                            sNotifyMsg = sNotifyMsg & "<p>Reference No. : " & .MotherID & "</p>"
                            sNotifyMsg = sNotifyMsg & "<p>Filename : " & sFilename & "</p>"
                            sNotifyMsg = sNotifyMsg & "<p>Date time received : " & Now & "</p>"
                            sNotifyMsg = sNotifyMsg & "<p>Remarks : " & Trim(txtUploadRemarks.Text) & "</p>"
                            Mailhelper.MailHelper.SendMailMessage("noreply@medicardphils.com", sSender, "", "", sTitle, sNotifyMsg)
                        End If

                    End Using

                    'Mailhelper.MailHelper.SendMailMessage(.uploaded_by, "mgabat@medicardphils.com", "ctubig@medicardphils.com", "ctubig@medicardphils.com", sTitle, sMsg)
                End Using

            End With
            Response.Redirect("RequesDetails.aspx?t=" & Request.QueryString("t") & "&c=" & HttpUtility.UrlEncode(Request.QueryString("c")) & "&u=" & HttpUtility.UrlEncode(Request.QueryString("u")) & "&a=" & HttpUtility.UrlEncode(Request.QueryString("a")) & "&dtl=" & HttpUtility.UrlEncode(Request.QueryString("dtl")))
        End Using
    End Sub

    Protected Sub Send_Email()

    End Sub
End Class